config/routes.rb
Rails.application.routes.draw do
  root 'urls#new'
  resources :urls, only: %i[index show new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
require 'csv'

class Url < ApplicationRecord
  validates :original, :link, :visits, presence: true

  def self.to_csv
    attributes = %w[original link visits]

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.find_each do |url|
        csv << attributes.map { |attr| url.send(attr) }
      end
    end
  end

  def self.csv_filename
    "urls-#{Time.zone.today}-#{SecureRandom.hex(4)}.csv"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def index
    @urls = Url.all.order(created_at: :asc)

    respond_to do |format|
      format.html
      format.csv { send_data @urls.to_csv, filename: @urls.csv_filename }
    end
  end

  def show
    # TODO: rename link to token
    service = RedirectService.new(link: params[:link])

    if service.call
      redirect_to service.redirect_url
    else
      # TODO: in general: add success and error objects with messages to pass here
      redirect_to urls_path, alert: 'Wrong URL.'
    end
  end

  def new
    @form = CreateUrlForm.new
  end

  def create
    @form = CreateUrlForm.new(url_params)
    service = CreateUrlService.new(form: @form)

    if service.call
      redirect_to urls_path, notice: 'Url was successfully created.'
    else
      render :new
    end
  end

  private

  def url_params
    params.require(:url_form).permit(:original)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlAndPepper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/_form.html.erb
<%= simple_form_for(@form, as: :url_form, url: urls_path) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :original, label: 'Url to be shortened' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Shorten!' %>
  </div>
<% end %>

app/views/urls/index.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<h1>Urls</h1>

<table>
  <thead>
    <tr>
      <th>Original</th>
      <th>Link</th>
      <th>Visits</th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url.original %></td>
        <td><%= link_to "#{request.base_url}/#{url.link}", url_path(url, link: url.link) %></td>
        <td><%= url.visits %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Url', new_url_path %>
<%= link_to 'Download CSV', urls_path(format: :csv) %>

app/views/urls/new.html.erb
<h1>New Url</h1>

<%= render 'form', url: @url %>

<%= link_to 'Back', urls_path %>